// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHLZheRPGXqcOYbiol1kL-Axmowjqmz_Y',
    appId: '1:317931464094:web:8e6ee7b34b1f480224628f',
    messagingSenderId: '317931464094',
    projectId: 'cloud-functions-demo-ca158',
    authDomain: 'cloud-functions-demo-ca158.firebaseapp.com',
    storageBucket: 'cloud-functions-demo-ca158.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjzuwZZwquotJbjfKAwu0TpnMdhrf5Sas',
    appId: '1:317931464094:android:b3addf82983fe31a24628f',
    messagingSenderId: '317931464094',
    projectId: 'cloud-functions-demo-ca158',
    storageBucket: 'cloud-functions-demo-ca158.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHLZheRPGXqcOYbiol1kL-Axmowjqmz_Y',
    appId: '1:317931464094:web:dabef8f7b45e26d624628f',
    messagingSenderId: '317931464094',
    projectId: 'cloud-functions-demo-ca158',
    authDomain: 'cloud-functions-demo-ca158.firebaseapp.com',
    storageBucket: 'cloud-functions-demo-ca158.firebasestorage.app',
  );
}
