// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1XLUahGbKorC5ILkUTr6bGn_GacZiMJ8',
    appId: '1:424501599220:web:306b5a8d5e53aa688537a1',
    messagingSenderId: '424501599220',
    projectId: 'pid-main-project',
    authDomain: 'pid-main-project.firebaseapp.com',
    storageBucket: 'pid-main-project.appspot.com',
    measurementId: 'G-6F281DN0C1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0x8Z77NEKbbKJYuuGDXqJZEufvFQARnU',
    appId: '1:424501599220:android:f7f5e661df4f9c648537a1',
    messagingSenderId: '424501599220',
    projectId: 'pid-main-project',
    storageBucket: 'pid-main-project.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1XLUahGbKorC5ILkUTr6bGn_GacZiMJ8',
    appId: '1:424501599220:web:e3c3118317819f0d8537a1',
    messagingSenderId: '424501599220',
    projectId: 'pid-main-project',
    authDomain: 'pid-main-project.firebaseapp.com',
    storageBucket: 'pid-main-project.appspot.com',
    measurementId: 'G-RJVCG8KL8W',
  );
}
