name: pdi_main_project
description: "PDI project - Flutter didactics support system."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1
environment:
  sdk: ^3.5.3

# To see which dependencies have newer versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  cloud_firestore: ^5.4.4
  cloud_functions: ^5.1.5
  mocktail: ^1.0.4
  firebase_performance: ^0.10.1+5
  firebase_storage: ^12.4.5
  file_picker: ^10.1.2
  path: ^1.9.0
  url_launcher: ^6.3.1
  path_provider: ^2.1.5
  dio: ^5.8.0+1
  open_file: ^3.5.10
  universal_html: ^2.2.4
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  # The lint set provided by the package is activated in the `analysis_options.yaml` file
  flutter_lints: ^5.0.0
  firebase_core_platform_interface: ^5.3.0

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package
