// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7kwpq_TrOHJ79VhxHEshwNLJNbL3k3Jg',
    appId: '1:796057706163:web:a8a881d0d7eb0a1ce2dac6',
    messagingSenderId: '796057706163',
    projectId: 'fir-crud-18074',
    authDomain: 'fir-crud-18074.firebaseapp.com',
    storageBucket: 'fir-crud-18074.appspot.com',
    measurementId: 'G-YP2CVX1NDN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnNZf_3qAf0f5-m6g3imEpvb9OFpM8IdM',
    appId: '1:796057706163:android:f14535fa5086f288e2dac6',
    messagingSenderId: '796057706163',
    projectId: 'fir-crud-18074',
    storageBucket: 'fir-crud-18074.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7kwpq_TrOHJ79VhxHEshwNLJNbL3k3Jg',
    appId: '1:796057706163:web:ebba02e1e03a8f8de2dac6',
    messagingSenderId: '796057706163',
    projectId: 'fir-crud-18074',
    authDomain: 'fir-crud-18074.firebaseapp.com',
    storageBucket: 'fir-crud-18074.appspot.com',
    measurementId: 'G-VE13X6Q12P',
  );
}
